name: my_skin_cancer_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'




#---------------------PACKAGES ------------------------------------#


dependencies:
  flutter:
    sdk: flutter

#Utility Packages
  flutter_native_splash: ^2.3.11
  image_picker: ^1.1.0
  
  #Icons
  cupertino_icons: ^1.0.2
  tflite_v2: ^1.0.0
  url_launcher: ^6.0.10
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  flutter_settings_screens: ^0.3.4

#---------------------PACKAGES END ------------------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:
  uses-material-design: true





  #---------------------LOCAL ASSETS ------------------------------------#
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/model/

  
  

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
